version: "3.9"
services:
  postgres:
    image: postgres
    volumes:
      - postgres_db_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - public
      - internal

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@pgadmin.com #the username to login to pgadmin
      PGADMIN_DEFAULT_PASSWORD: pgadmin # the password to login to pgadmin
    ports:
      - "5050:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json # preconfigured servers/connections
    depends_on:
      - postgres
    networks:
      - public
      - internal

networks:
  internal:
  public:
    driver: bridge

volumes:
  postgres_db_data: